### ISSUE TITLE
No response was returned.

### ISSUE THREAD

**Issue by lunar-night** [py-mine/mcstatus#331]
Dear mcstatus.

I have been avile for the past few days on a bot that can get the status of Minecraft servers using heroku & discord.py & mcstatus.
But an error occurs...

[main.py link](https://github.com/lunar-night/Final-Bot/blob/5e354e911f7de0d39295e49cd5f9eac72383676d/src/main.py#L39) 
`2022-06-21T09:13:20.957947+00:00 app[final-bot.1]: Traceback (most recent call last):
2022-06-21T09:13:20.957948+00:00 app[final-bot.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/discord_slash/client.py", line 1352, in invoke_command
2022-06-21T09:13:20.957949+00:00 app[final-bot.1]:     await func.invoke(ctx, **args)
2022-06-21T09:13:20.957949+00:00 app[final-bot.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/discord_slash/model.py", line 210, in invoke
2022-06-21T09:13:20.957950+00:00 app[final-bot.1]:     return await self.func(*args, **kwargs)
2022-06-21T09:13:20.957951+00:00 app[final-bot.1]:   File "/app/src/main.py", line 39, in status_command
2022-06-21T09:13:20.957951+00:00 app[final-bot.1]:     server = JavaServer.lookup(arg1, arg2)
2022-06-21T09:13:20.957952+00:00 app[final-bot.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/mcstatus/server.py", line 57, in lookup
2022-06-21T09:13:20.957952+00:00 app[final-bot.1]:     addr = minecraft_srv_address_lookup(address, default_port=25565, lifetime=timeout)
2022-06-21T09:13:20.957956+00:00 app[final-bot.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/mcstatus/address.py", line 198, in minecraft_srv_address_lookup
2022-06-21T09:13:20.957957+00:00 app[final-bot.1]:     answers = dns.resolver.resolve("_minecraft._tcp." + host, RdataType.SRV, lifetime=lifetime)
2022-06-21T09:13:20.957957+00:00 app[final-bot.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/dns/resolver.py", line 1193, in resolve
2022-06-21T09:13:20.957958+00:00 app[final-bot.1]:     return get_default_resolver().resolve(qname, rdtype, rdclass, tcp, source,
2022-06-21T09:13:20.957958+00:00 app[final-bot.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/dns/resolver.py", line 1066, in resolve
2022-06-21T09:13:20.957958+00:00 app[final-bot.1]:     timeout = self._compute_timeout(start, lifetime,
2022-06-21T09:13:20.957959+00:00 app[final-bot.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/dns/resolver.py", line 878, in _compute_timeout
2022-06-21T09:13:20.957959+00:00 app[final-bot.1]:     if duration >= lifetime:
2022-06-21T09:13:20.957960+00:00 app[final-bot.1]: TypeError: '>=' not supported between instances of 'float' and 'str'`
Python: 3.10.5
Discord.py: 1.7.3
mcstatus: 9.0.1

Where did I go wrong?
Please tell me Answer.

**Comment by lunar-night** [comment]
oh, Sorry for my bad English.
I am a Japanese student :(

**Comment by lunar-night** [comment]
Thank you for your quick reply.
I was able to solve the problem by converting to int type.
Thank you!
But I am stumped by the error that the server did not respond with any information.
What should I do?

**Comment by kevinkjt2000** [comment]
@lunar-night Are you seeing this? #316

**Comment by ItsDrike** [comment]
> But I am stumped by the error that the server did not respond with any information.

That just means the server is probably offline, or that mcstatus doesn't support it's version. If you've encountered this error on calling `query`, know that most minecraft servers don't support query protocol by default, it's something that needs to be specifically enabled in `server.properties` configuration file of the MC server.

I'd suggest wrapping the `query` call, as well as the ping call into `try-except` to handle for servers which aren't running, and servers which don't support query (which again, will be most servers). 

You may want to use `JavaServer.async_status` instead of query, status will run on pretty much any minecraft server unless it's too old (mcstatus doesn't support it), or is somehow customized to alter the status it returns (with some custom plugin), but that's very rare.

The status protocol is what minecraft clients use to display info about the server on the multiplayer server list screen. It includes the server description and number of online players, and server slot amount, and even some version info. Here' an example of using status:
![image](https://user-images.githubusercontent.com/20902250/174800212-54db4536-d488-470d-89be-00deef749992.png)

**Comment by lunar-night** [comment]
Thanks.
But the error came up again..
`2022-06-21T14:08:40.993804+00:00 app[final-bot.1]: An exception has occurred while executing command `status`:
2022-06-21T14:08:40.993814+00:00 app[final-bot.1]: Traceback (most recent call last):
2022-06-21T14:08:40.993815+00:00 app[final-bot.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/discord_slash/client.py", line 1352, in invoke_command
2022-06-21T14:08:40.993816+00:00 app[final-bot.1]:     await func.invoke(ctx, **args)
2022-06-21T14:08:40.993816+00:00 app[final-bot.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/discord_slash/model.py", line 210, in invoke
2022-06-21T14:08:40.993816+00:00 app[final-bot.1]:     return await self.func(*args, **kwargs)
2022-06-21T14:08:40.993817+00:00 app[final-bot.1]:   File "/app/src/main.py", line 44, in status_command
2022-06-21T14:08:40.993817+00:00 app[final-bot.1]:     server = await JavaServer.async_status(address)
2022-06-21T14:08:40.993817+00:00 app[final-bot.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/mcstatus/server.py", line 135, in async_status
2022-06-21T14:08:40.993818+00:00 app[final-bot.1]:     await connection.connect(self.address, self.timeout)
2022-06-21T14:08:40.993818+00:00 app[final-bot.1]: AttributeError: 'str' object has no attribute 'address'
`
