### ISSUE TITLE
TimeoutError while checking bedrock status

### ISSUE THREAD

**Issue by Rishit-Gupta-RG** [py-mine/mcstatus#432]
I get the following error while checking bedrock status on a discord bot 
``` 
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.10/site-packages/disnake/ext/commands/slash_core.py", line 730, in invoke
   await call_param_func(self.callback, inter, self.cog, **kwargs)
 File "/app/.heroku/python/lib/python3.10/site-packages/disnake/ext/commands/params.py", line 1022, in call_param_func
   return await maybe_coroutine(safe_call, function, **kwargs)
 File "/app/.heroku/python/lib/python3.10/site-packages/disnake/utils.py", line 596, in maybe_coroutine
   return await value
 File "/app/cogs/minecraft.py", line 16, in check
   status = server.status()
 File "/app/.heroku/python/lib/python3.10/site-packages/mcstatus/utils.py", line 65, in sync_wrapper
   raise last_exc  # type: ignore # (This won't actually be unbound)
 File "/app/.heroku/python/lib/python3.10/site-packages/mcstatus/utils.py", line 61, in sync_wrapper
   return func(*args, **kwargs)
 File "/app/.heroku/python/lib/python3.10/site-packages/mcstatus/server.py", line 215, in status
   return BedrockServerStatus(self.address, self.timeout, **kwargs).read_status()
 File "/app/.heroku/python/lib/python3.10/site-packages/mcstatus/bedrock_status.py", line 55, in read_status
   data, _ = s.recvfrom(2048)
TimeoutError: timed out
```
I am getting this error on both versions `v9.4.0` and `v10.0.1`, It used to work earlier but not working anymore, I didn't update anything in the code.

**Comment by PerchunPak** [comment]
Can't reproduce with `10.0.0` (patch inside `10.0.1` fixed answer object, it can't do anything with this issue)
```py
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mcstatus
>>> mcstatus.BedrockServer.lookup("play.histeria.fr").status()
<mcstatus.bedrock_status.BedrockStatusResponse object at 0x0000021AE5B5B820>
```
Could you give IP? Also, try to ping the server with https://mcsrvstat.us. If this worked before, when did it stop?

**Comment by Rishit-Gupta-RG** [comment]
The bot is hosted on [heroku](https://www.heroku.com). They use shared IP.
It was working properly 1 or 2 months ago, when I tried it today then it didn't work.

**Comment by PerchunPak** [comment]
I mean server's IP. Bot's IP doesn't matter.

**Comment by Rishit-Gupta-RG** [comment]
Minecraft serber's IP? it's `ggnetworkk.aternos.me:34624`

**Comment by PerchunPak** [comment]
Still can't reproduce
```py
>>> mcstatus.BedrockServer.lookup("ggnetworkk.aternos.me:34624").status()
<mcstatus.bedrock_status.BedrockStatusResponse object at 0x0000014A230EB820>
```
Send your code, please.

**Comment by Rishit-Gupta-RG** [comment]
```py
        server = BedrockServer.lookup('ggnetworkk.aternos.me:34624')
        status = server.status()
        if status.players_max == 1:
            its = "online"
        else:
            its = "offline"```

**Comment by PerchunPak** [comment]
Did you try to ping your server from your computer? (not heroku)

**Comment by Rishit-Gupta-RG** [comment]
Gives an error, it waits for few seconds & gives an error
```
Traceback (most recent call last):
  File "C:\test.py", line 4, in <module>
    status = server.status()
  File "C:\Users\New\AppData\Local\Programs\Python\Python39\lib\site-packages\mcstatus\utils.py", line 66, in sync_wrapper
    raise last_exc  # type: ignore # (This won't actually be unbound)
  File "C:\Users\New\AppData\Local\Programs\Python\Python39\lib\site-packages\mcstatus\utils.py", line 62, in sync_wrapper
    return func(*args, **kwargs)
  File "C:\Users\New\AppData\Local\Programs\Python\Python39\lib\site-packages\mcstatus\server.py", line 213, in status
    return BedrockServerStatus(self.address, self.timeout, **kwargs).read_status()
  File "C:\Users\New\AppData\Local\Programs\Python\Python39\lib\site-packages\mcstatus\bedrock_status.py", line 49, in read_status
    data = self._read_status()
  File "C:\Users\New\AppData\Local\Programs\Python\Python39\lib\site-packages\mcstatus\bedrock_status.py", line 58, in _read_status
    data, _ = s.recvfrom(2048)
socket.timeout: timed out
```
Exact code:
```python
from mcstatus import BedrockServer
server = BedrockServer.lookup('ggnetworkk.aternos.me:34624')
status = server.status()
if status.players_max == 1:
      its = "offline"
else:
      its = "online"
print(its)

**Comment by PerchunPak** [comment]
Works to me, @ItsDrike @kevinkjt2000 could you look at it?

**Comment by Rishit-Gupta-RG** [comment]
Now suddenly it starts working locally but doesn't work on bot.

**Comment by PerchunPak** [comment]
If it's working locally, you should write Heroku's support. This is their side problem.

**Comment by Rishit-Gupta-RG** [comment]
I think issue is something else, sometimes it works but sometimes it doesn't.
![image](https://user-images.githubusercontent.com/83908451/200187876-64a184e8-aacf-4b18-8a4c-e41355a1f809.png)

**Comment by PerchunPak** [comment]
Maybe atternos not always responses on pings? Anyway, this doesn't look like our side problem.

**Comment by Rishit-Gupta-RG** [comment]
I asked their staff, it does respond to ping always.

**Comment by PerchunPak** [comment]
Who? Bot? So issue can be closed?

**Comment by Rishit-Gupta-RG** [comment]
it means aternos

**Comment by PerchunPak** [comment]
Oh, it is expected. You should better ask Heroku.

**Comment by Rishit-Gupta-RG** [comment]
As [I said](https://github.com/py-mine/mcstatus/issues/432#issuecomment-1304861550) it does not work on my pc too sometimes, I client is not a problem, it's something else and doesn't seem like rate limits

**Comment by Rishit-Gupta-RG** [comment]
This is what the site gives
![image](https://user-images.githubusercontent.com/83908451/200188682-0425e6ed-f220-4276-a36b-174f5a411a0b.png)

**Comment by PerchunPak** [comment]
Are you sure that server still active?

**Comment by Rishit-Gupta-RG** [comment]
nvm, my mistake it wasn't

**Comment by kevinkjt2000** [comment]
The code printed "offline" when I tried it. It would seem as if whatever machine the bot is running on is suffering from some resource issue or firewall. If this code works on multiple other machines, there's obviously no issue with mcstatus...
