### ISSUE TITLE
TimeoutError: timed out

### ISSUE THREAD

**Issue by LLIaMMaH** [py-mine/mcstatus#629]
Good afternoon.
I tried your solution. Apparently it is a little outdated, since it returns an error. I took the code from you - https://mcstatus.readthedocs.io/en/stable/examples/player_list_from_query_with_fallback_on_status/
```
Traceback (most recent call last):
  File "/APP01/main3.py", line 4, in <module>
    query = server.query()
  File "/APP01/env/lib/python3.10/site-packages/mcstatus/server.py", line 168, in query
    return self._retry_query(Address(ip, self.address.port))
  File "/APP01/env/lib/python3.10/site-packages/mcstatus/utils.py", line 67, in sync_wrapper
    raise last_exc  # type: ignore # (This won't actually be unbound)
  File "/APP01/env/lib/python3.10/site-packages/mcstatus/utils.py", line 63, in sync_wrapper
    return func(*args, **kwargs)
  File "/APP01/env/lib/python3.10/site-packages/mcstatus/server.py", line 174, in _retry_query
    querier.handshake()
  File "/APP01/env/lib/python3.10/site-packages/mcstatus/querier.py", line 55, in handshake
    packet = self._read_packet()
  File "/APP01/env/lib/python3.10/site-packages/mcstatus/querier.py", line 48, in _read_packet
    packet.receive(self.connection.read(self.connection.remaining()))
  File "/APP01/env/lib/python3.10/site-packages/mcstatus/protocol/connection.py", line 584, in read
    result.extend(self.socket.recvfrom(self.remaining())[0])
TimeoutError: timed out
```

**Comment by ItsDrike** [comment]
This can happen when query isn't enabled on the server. Servers can only return query if they have it enabled in `server.properties` (the server owner must do this).

That said, considering the example in the docs is supposed to provide a "fallback" to query, that uses status, I agree that it should probably be updated.

**Comment by LLIaMMaH** [comment]
_I stopped the server, changed the `enable-query` value in the server management `server.properties` to `true` and started the server again, but the error did not go away._

Thank you very much for your example.
There are actually 2 typos in it:
def print_server_players - print_server_address
except TImeoutError: - TimeoutError

**Comment by ItsDrike** [comment]
Ah, thanks for pointing those out, I just quickly wrote this directly from the github UI, so I didn't really check for typos. But I'm glad it worked for you.

> I stopped the server, changed the enable-query value in the server management server.properties to true and started the server again, but the error did not go away.

That is a bit tricker to solve. There's 2 general reasons why this might be failing:

### Firewall

Query uses UDP network traffic (unlike status which uses TCP). Many firewalls block UDP connections, so if you're running this in some server rather than on your personal machine, you might be running into that.

The other possibility is that the minecraft hosting your server is running on isn't allowing UDP, in which case it's their firewall that's blocking this traffic.  This is actually fairly common with a bunch of these hostings. If this is the case, the only real way to get around it would then be to switch to another hosting provider.

### Wrong port

Another consideration to make is that query might be running on a different port than the server itself, `JavaServer.lookup` will find the TCP port for that server, this is the port you would use to connect to this server from a minecraft launcher, and through it you can get status info. 

In `server.properties`, there's `query-port` setting (or something like that, don't quote me on the exact name of the setting), which controls the UDP port used for query. If this port isn't the same as the regular `port`, query won't be able to run with this example.

If this is the case, and you don't want to set the port to the same one as the TCP port, you can work around it, but it is annoying. To do so, you will need to manually specify the port in lookup, and you'll need to do lookup twice, once for query, and second time for status, as the ports are different.

```py
query_server = JavaServer.lookup("127.0.0.1:25568")  # assuming your query port is 25568

...  # code to try out query

# if query failed (above the try: status = ... block)
status_server = JavaServer.lookup("127.0.0.1:25565")  # assuming your TCP port is 25565

... # rest of the code for getting status
```

**Comment by LLIaMMaH** [comment]
Thank you very much for the clarification. I have a personal server and now I wanted to write a TelegramBot in which it will be possible to monitor the status of the server.
On all servers I have a standard port of 25565 and all traffic goes through a reverse proxy (https://github.com/lhridder/infrared). I took all the examples from your documentation page and only query = server.query() did not work and gave an error.
```python
@logger.catch
def print_names():
    query = server.query()
    print(f"The server has the following players online: {', '.join(query.players.names)}")
```

**Comment by PerchunPak** [comment]
Can you also try to get query without your reverse-proxy? It might not support UDP

**Comment by LLIaMMaH** [comment]
Yes I can. After all, the servers are located on the local network, despite the fact that they are deployed on Proxmox.
But with your latest example on exception handling and enabling `enable-query` in the server settings, players began to appear, albeit with a slight delay.
Do you just want to see the result and compare it?

**Comment by ItsDrike** [comment]
The players you're seeing are almost certainly coming from status, not from query, query is a better choice, because status is not that precise, it only gives you a small number of players (like say 10 players, even if the server has 100 players online). This is why it's called a "sample" (`status.players.sample`).

Status can also be modified by plugins to put advertisements in there, or to just make it empty regardless of who's online. Since you're the server owner, you can of course just avoid installing these plugins, so this isn't necessarily an issue for you, but it's yet another reason to generally prefer query if you want reliable information about players. (Most servers don't have query enabled though).

The reason for the delay is then because you're first making a query, and since mcstatus can't seem to be able to access query, it waits until a 3 second timeout, and then it tries again, up to 3 times. With status, you can reduce the retry count by passing `server.status(tries=1)`, this doesn't currently work with query though, that's a bug, it will be fixed in a future version.

If you really don't want query, you can tremendously reduce the time it takes to get the data by always preferring status, getting status should work every time, for every supported minecraft server implementation:

```py
server = JavaServer.lookup("...")
status = server.status()
print("Players online:", ", ".join([player.name for player in status.players.sample]))
````

But again, ideally you'd really want to use query here instead of status.

**Comment by LLIaMMaH** [comment]
Maybe it's worth making additional methods for getting players, mods and plugins?

I could be wrong, but local queries and parameter changes began to be executed very, very quickly.
```python
server = JavaServer.lookup("192.168.1.25:25565", timeout=1)
...
# 'query' has to be enabled in a server's server.properties file!
# It may give more information than a ping, such as a full player list or mod information.
server.status(tries=1)
query = server.query()
print(f"The server has the following players online: {', '.join(query.players.names)}")
```
Error: time exceeded is no longer displayed.

**Comment by ItsDrike** [comment]
> Maybe it's worth making additional methods for getting players, mods and plugins?

Mcstatus obtains the data you see here through various interactions with the minecraft protocol. We can't just invent a new way to obtain the players, and make it easier to get them reliably, because servers simply don't give us this information.

Java minecraft servers primarily expose their information through status. This is used by the minecraft launcher to show you some details about the server in the multiplayer screen. This is why we can get something like the MOTD, amount of slots and online players.

The player sample in status is actually something that you can see in the launcher when you hover over the slot count. This is why many servers put advertisements there, instead of actually giving you the list of players. It's also why this list of players is limited to only a few players, instead of giving you all of them. If a server has 1000 online players, the launcher wouldn't be able to create a window big enough to show you all of those anyway. So to save some bandwidth, only a small sample of the connected players is actually sent by the server.

Mcstatus then gives you a method to perform this status request, receiving a status response from the server. This response contains various things, which mcstatus parses and exposes to you in a nice way, one of the things that this response contains is indeed the player sample.

On the other hand, query is something that servers can optionally enable, and is used precisely for the purpose of being able to get some reliable information from the server, which can be used by various external tools. It's disabled by default though, since it can expose this information to everyone, and many server owners don't necessarily want to do that. (Query doesn't really contain anything that sensitive to the point where it would be a security risk to enable it, it just has info on the minecraft version and server implementation you're using, motd and the player list. It's more about just preventing some scripts from constantly checking who is online - privacy reasons).

This is why you should prefer query if you can, it's just that you usually can't. In this case, you own the server, so you should be able to enable query and use it. If it doesn't work, it's almost certainly due to a misconfigured network that doesn't let UDP traffic through. The query function should work reliably for pretty much all server implementations, unless you're using something really esoteric.

---

As for the other suggestions, of adding methods to get mods and plugins:

- It's not really possible to obtain plugins from a server, they simply aren't exposed by neither query nor status  (and for a good reason, you wouldn't want people to know which anti-cheat you're using for example). 
- With mods, there is already a PR that adds support for getting data from forge servers (#578).

Getting plugins might be possible by going through a full login sequence, and actually having a user join the server for a while. this bot user could then execute a command to get plugins and we could read the chat response back. However this command is often only available for op users, so it generally wouldn't work anyway.

Also, for online servers (that is, non-warez servers, that only allows people with purchased minecraft accounts to join), it can be really annoying to configure everything up, as there's a lot of things you need to do for it. For that reason, mcstatus will almost certainly never implement logic to do something like this.

There is another library called [mcproto](https://github.com/py-mine/mcproto) under the py-mine github organization (disclaimer: I maintain this library). With it, you can actually make it past login, and do some more interesting things, but it's not trivial, even with the library, and mcproto is still WIP. You can read a bit about how to set up authentication with mcproto if you're really interested, but it is annoying (and there's not much mcproto can even do about this, as is explained): [in the mcproto docs](https://mcproto.readthedocs.io/en/stable/usage/authentication/). Here's some example code that performs login with a server using mcproto: [paste.gg](https://paste.gg/p/ItsDrike/ac1f24142fdf4c64aa72b05e76579c01)

**Comment by LLIaMMaH** [comment]
Wonderful. It’s great that there is a project that allows you to authorize and connect to the server. But I meant something a little different. After executing `status` or `query`, you can not go through the received data array yourself, but simply look at the counter and display a list if necessary.
```python
print(f"The server has the following players online: {', '.join(query.players.names)}")
```
As an example:
```python
server = JavaServer.lookup("address")
status = server.status()
if status.players.online > 0:
  query = server.query()
  players_list = query.players.names
  for player in players_list:
    print(f"{player.name} - {player.id}")
```
A dictionary would be handy to save in a player's database.

**Comment by LLIaMMaH** [comment]
I asked about mods and plugins because I saw it here - https://api.mcstatus.io/v2/status/java/gtnh.jdi.su
Here you can see the documentation - https://mcstatus.io/docs
To be honest, at first I thought it was your project. But when I went to their github I realized that this is a separate project and it was written not in python, but in GO.

**Comment by PerchunPak** [comment]
> It's not really possible to obtain plugins from a server, they simply aren't exposed by neither query nor status (and for a good reason, you wouldn't want people to know which anti-cheat you're using for example).

`bukkit.yml` or `spigot.yml` (don't really remember) has an `query-plugins` option, that exposes the list of plugins into query. Also, you should just close your query port for outside world and host the telegram bot on the same machine with the server, so you don't need to care about privacy/security so much.

>  To be honest, at first I thought it was your project. But when I went to their github I realized that this is a separate project and it was written not in python, but in GO.

Yes, it is hard to devise a unique name for this theme. You can also check out my similar project, which is written using mcstatus - [StatusMC](https://statusmc.perchun.it) (as I said, naming is hard here).

**Comment by PerchunPak** [comment]
P.S. I didn't implement mods support in StatusMC because I am waiting for #578. Although, you can extract the mods from `additional` field.

But you really should just use mcstatus, because such websites add additional unnecessary network communication, and it would be useful only if you use non-Python language, can't use mcstatus directly or there is no library for Minecraft in your language. You can also use those if you really like some additional features, like modular system (you can get status and query response in one HTTP request), but this is not really your case, as you do not just ping some random servers, and I would rather close query for outside world.

**Comment by ItsDrike** [comment]
> After executing `status` or `query`, you can not go through the received data array yourself, but simply look at the counter and display a list if necessary.

So, what you're suggesting is a method that internally uses query and status, and you can just call it immediately? I don't think that's a good idea, since we'd be expected to provide functions like that for every little thing, i.e. `get_minecraft_version`, `get_online_players`, `get_player_slots_amount`, etc. Each one of these methods would call query or status internally, obtain all of the data at once, and then only give you access to one specific thing.

This would very likely lead people to call a bunch of these methods if they wanted various things, for example someone might want both version, slot amount and the player list. Calling all 3 methods would result in making the same request 3 times, each time we get all of the data, but we only give you one specific thing, and throw away the rest.

I think it's a good thing to allow people to see that by enabling query, you get all of these things at once, from a single request. How you use those things is then up to you, you can ignore the rest and only use the one thing you care about, but if you do care about a whole bunch of info on the server, you can get all of it at once.

This is both faster, and it impacts the server less. If someone made a program requesting 10 different things from a server, it would spam the server with a bunch of status request packets, all of which giving you the same data over and over. If you over do this, it might even yield to you getting banned by the server for suspected DoS (denial of service attack). You're simply making needless requests over and over again, and the server you're requesting this from will have to handle that.

I also don't think that it's particularly difficult to learn how mcstatus works, as we have a relatively simple to use public API for the library, and the response objects are all documented and type-hinted.

**Comment by LLIaMMaH** [comment]
In no case did I suggest doing query or status every time. I just suggested creating a method that would pull out a dictionary from the existing data.
I apologize for my bad English.

**Comment by ItsDrike** [comment]
I don't understand what you mean by "pulling out a dictionary from the existing data". Like represent the data as a dictionary, rather than have it in the response classes? You can access `status.raw` which will give you a dictionary of the received data, exactly as it was received from the server.

However this data is unparsed, so for example the motd may be hard to work with in comparison to using `status.motd`, which gives you back an instance of the `Motd` class, that contains some neat logic allowing you to get various representations of the motd (such as pure text, ignoring any colors and formatting), minecraft formatting with the section/paragraph signs (like §a for green), and some other things.

![image](https://github.com/py-mine/mcstatus/assets/20902250/a57db292-a3c5-4585-9899-9f393ef742d4)

**Comment by ItsDrike** [comment]
Also, this discussion went pretty off topic from the original issue by now, github issues aren't really a great place for bikeshedding, they're here to report a bug, propose a feature, or ask questions about a single thing. Not to discuss the project as a whole. If you're interested in those kinds of discussions, consider visiting our discord instead: https://discord.gg/C2wX7zduxC

As for the original question/issue, as I've mentioned query timing out just means mcstatus wasn't able to make a connection to the server. This is likely due to a misconfiguration in your network, which ends up blocking UDP traffic. Try making the request directly from the same server where the minecraft server is running, and use a local IP in lookup. If this also doesn't work, make absolutely certain that you've saved the `server.properties` file with query enabled, and restarted the server afterwards. Also make sure that query-port is the same as the server port you're using for all TCP traffic.

If none of these suggestions worked for you, we'll need a minimal reproducable example. Since you're running a minecraft full server here, please provide us with the exact steps to recreate it, so that we can test this ourselves and figure out what's wrong. 

If you're using docker, this can just mean giving us the docker image, and all of the plugins that you're using. Otherwise, we'll need to know the operating system you're using, and have the exact instructions you've used from after installing this operating system to set up the minecraft server (and again a list of all plugins you've used).

I would suggest to first try and remove all plugins and see if it works then, if so, just keep adding plugins until it stops working, so you can figure out which plugin is causing the issue. If it doesn't it's the server distribution itself, which is odd, as it likely means it doesn't conform to the established minecraft protocol standard. In this case, we'll need the details I mentioned above.

**Comment by LLIaMMaH** [comment]
Thank you very much. As I already wrote above, everything works, your advice with limiting the timings helped.
